# Generated by Django 4.1.7 on 2023-06-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_id", models.AutoField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=10)),
                ("emp_birth", models.DateField()),
                ("emp_gender", models.CharField(max_length=1)),
                ("emp_address", models.CharField(max_length=45)),
                ("emp_phone", models.CharField(max_length=45)),
                ("emp_account", models.CharField(max_length=45)),
                ("emp_email", models.EmailField(max_length=254)),
                ("emp_plus", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Wage_hourly",
            fields=[
                ("wag_id", models.AutoField(primary_key=True, serialize=False)),
                ("wag_info", models.CharField(max_length=10)),
                ("wag_price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Schedulefix",
            fields=[
                ("sch_id", models.AutoField(primary_key=True, serialize=False)),
                ("sch_date", models.DateField()),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule_exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee1",
                    models.ForeignKey(
                        db_column="emp_id1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_employee1",
                        to="management.employee",
                    ),
                ),
                (
                    "employee2",
                    models.ForeignKey(
                        db_column="emp_id2",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_employee2",
                        to="management.employee",
                    ),
                ),
                (
                    "schedule1",
                    models.ForeignKey(
                        db_column="sch_id1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_schedule1",
                        to="management.schedulefix",
                    ),
                ),
                (
                    "schedule2",
                    models.ForeignKey(
                        db_column="sch_id2",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_schedule2",
                        to="management.schedulefix",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("not_id", models.AutoField(primary_key=True, serialize=False)),
                ("not_title", models.CharField(max_length=50)),
                ("not_contents", models.CharField(max_length=200)),
                (
                    "employee_notice",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Absenteeism",
            fields=[
                ("abs_id", models.AutoField(primary_key=True, serialize=False)),
                ("abs_start", models.DateTimeField()),
                ("abs_finish", models.DateTimeField()),
                ("abs_totalmin", models.IntegerField(default=0)),
                ("abs_totalwage", models.IntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.employee",
                    ),
                ),
                (
                    "wageinfo",
                    models.ForeignKey(
                        db_column="wag_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.wage_hourly",
                    ),
                ),
            ],
        ),
    ]
