# Generated by Django 4.1.7 on 2023-06-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absenteeism",
            name="abs_finish",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="absenteeism",
            name="wageinfo",
            field=models.ForeignKey(
                blank=True,
                db_column="wag_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.wage_hourly",
            ),
        ),
    ]
