# Generated by Django 4.1.7 on 2023-06-08 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_absenteeism_abs_finish_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule_exchange",
            name="schedule1",
        ),
        migrations.RemoveField(
            model_name="schedule_exchange",
            name="schedule2",
        ),
        migrations.RemoveField(
            model_name="schedulefix",
            name="sch_date",
        ),
        migrations.AddField(
            model_name="schedule_exchange",
            name="end1",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 8, 21, 8, 26, 445648)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule_exchange",
            name="end2",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 8, 21, 8, 30, 448509)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule_exchange",
            name="start1",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 8, 21, 8, 34, 462283)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule_exchange",
            name="start2",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 8, 21, 8, 38, 160227)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedulefix",
            name="time_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="schedulefix",
            name="time_start",
            field=models.DateTimeField(),
        ),
    ]
