# Generated by Django 4.1.7 on 2023-06-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_remove_schedule_exchange_schedule1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedulefix",
            old_name="time_end",
            new_name="sch_end",
        ),
        migrations.RenameField(
            model_name="schedulefix",
            old_name="time_start",
            new_name="sch_start",
        ),
    ]
