# Generated by Django 4.1.7 on 2023-06-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_rename_time_end_schedulefix_sch_end_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedulefix",
            old_name="sch_end",
            new_name="sch_finish",
        ),
    ]
