# Generated by Django 4.1.7 on 2023-06-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_rename_sch_end_schedulefix_sch_finish"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule_exchange",
            name="approval",
            field=models.BooleanField(default=False),
        ),
    ]
