# Generated by Django 4.1.7 on 2023-06-08 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_schedule_exchange_approval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="employee_notice",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="not_contents",
        ),
        migrations.AddField(
            model_name="notice",
            name="not_content",
            field=models.TextField(default=1, verbose_name="내용"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notice",
            name="not_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 8, 12, 39, 6, 512889, tzinfo=datetime.timezone.utc
                ),
                verbose_name="등록시간",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notice",
            name="not_writer",
            field=models.ForeignKey(
                db_column="emp_email",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.employee",
                verbose_name="작성자",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notice",
            name="not_title",
            field=models.CharField(max_length=128, verbose_name="제목"),
        ),
    ]
