# Generated by Django 4.1.7 on 2023-06-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_remove_notice_employee_notice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="not_writer",
            field=models.CharField(max_length=128, verbose_name="작성자"),
        ),
    ]
