# Generated by Django 4.1.7 on 2023-06-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_alter_notice_not_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule_exchange",
            name="start1",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="start2",
            field=models.DateTimeField(null=True),
        ),
    ]
