# Generated by Django 4.1.7 on 2023-06-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_alter_schedule_exchange_start1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_name",
            field=models.CharField(max_length=20),
        ),
    ]
