# Generated by Django 4.1.7 on 2023-06-12 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_alter_employee_emp_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule_exchange",
            name="end1",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="start2",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 12, 15, 50, 18, 29310, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
